unit uIntOrdemServico;

interface

uses uIntEndereco;

type
  TIntOrdemServico = class(TObject)
  private
    FCodOrdemServico: Integer;
    FNumOrdemServico: Integer;
    FCodPessoaProdutor: Integer;
    FSglProdutor: String;
    FNomProdutor: String;
    FNumCNPJCPFProdutor: String;
    FCodPropriedadeRural: Integer;
    FNomPropriedadeRural: String;
    FNumImovelReceitaFederal: String;
    FCodPessoaTecnico: Integer;
    FNomTecnico: String;
    FNumCNPJCPFTecnico: String;
    FCodPessoaVendedor: Integer;
    FNomVendedor: String;
    FNumCNPJCPFVendedor: String;
    FQtdAnimais: Integer;
    FNumSolicitacaoSISBOV: Integer;
    FCodPaisSISBOVInicial: Integer;
    FCodEstadoSISBOVInicial: Integer;
    FCodMicroRegiaoSISBOVInicial: Integer;
    FCodAnimalSISBOVInicial: Integer;
    FNumDVSISBOVInicial: Integer;
    FCodFormaPagamentoOS: Integer;
    FFDesFormaPagamentoOS: String;
    FEnderecoEntregaCert: TIntEndereco;
    FCodIdentificacaoDupla: Integer;
    FSglIdentificacaoDupla: String;
    FDesIdentificacaoDupla: String;
    FCodFabricanteIdentificador: Integer;
    FNomReduzidoFabricante: String;
    FCodformaPagamentoIdent: Integer;
    FDesFormaPagamentoIdent: String;
    FEnderecoEntregaIdent: TIntEndereco;
    FEnderecoCobrancaIdent: TIntEndereco;
    FCodModeloIdentificador1: Integer;
    FSglModeloIdentificador1: String;
    FDesModeloIdentificador1: String;
    FCodModeloIdentificador2: Integer;
    FSglModeloIdentificador2: String;
    FDesModeloIdentificador2: String;
    FCodProdutoAcessorio1: Integer;
    FSglProdutoAcessorio1: String;
    FDesProdutoAcessorio1: String;
    FQtdProdutoAcessorio1: Integer;
    FCodProdutoAcessorio2: Integer;
    FSglProdutoAcessorio2: String;
    FDesProdutoAcessorio2: String;
    FQtdProdutoAcessorio2: Integer;
    FCodProdutoAcessorio3: Integer;
    FSglProdutoAcessorio3: String;
    FDesProdutoAcessorio3: String;
    FQtdProdutoAcessorio3: Integer;
    FNumPedidoFabricante: Integer;
    FCodArquivoRemessaPedido: Integer;
    FNumRemessa: Integer;
    FDtaCadastramento: TDateTime;
    FCodUsuarioCadastramento: Integer;
    FNomUsuariocadastramento: String;
    FDtaUltimaAlteracao: TDateTime;
    FCodUsuarioUltimaAlteracao: Integer;
    FNomUsuarioUltimaAlteracao: String;
    FCodSituacaoOS: Integer;
    FSglSituacaoOS: String;
    FDesSituacaoOS: String;
    FTxtObservacao: String;
    FNumCNPJCPFProdutorFormatado: String;
    FNumCNPJCPFTecnicoFormatado: String;
    FNumCNPJCPFVendedorFormatado: String;
    FIndEnviaPedidoIdentificador: String;
    FNomUsuarioPedido: String;
    FCodUsuarioPedido: Integer;
    FDtaPedido: TDateTime;
    FTxtObservacaoPedido: String;
    FIndAnimaisRegistrados: String;
    FDtaEnvio: TDateTime;
    FNomServicoEnvio: String;
    FNumConhecimento: String;
    FCodLocalizacaoSisbov: Integer;
    FCodBoleto: Integer;
    FIndTransmissaoSisbov: String;
  public
    property CodOrdemServico: Integer read FCodOrdemServico write FCodOrdemServico;
    property NumOrdemServico: Integer read FNumOrdemServico write FNumOrdemServico;
    property CodPessoaProdutor: Integer read FCodPessoaProdutor write FCodPessoaProdutor;
    property SglProdutor: String read FSglProdutor write FSglProdutor;
    property NomProdutor: String read FNomProdutor write FNomProdutor;
    property NumCNPJCPFProdutor: String read FNumCNPJCPFProdutor write FNumCNPJCPFProdutor;
    property CodPropriedadeRural: Integer read FCodPropriedadeRural write FCodPropriedadeRural;
    property NomPropriedadeRural: String read FNomPropriedadeRural write FNomPropriedadeRural;
    property NumImovelReceitaFederal: String read FNumImovelReceitaFederal write FNumImovelReceitaFederal;
    property CodPessoaTecnico: Integer read FCodPessoaTecnico write FCodPessoaTecnico;
    property NomTecnico: String read FNomTecnico write FNomTecnico;
    property NumCNPJCPFTecnico: String read FNumCNPJCPFTecnico write FNumCNPJCPFTecnico;
    property CodPessoaVendedor: Integer read FCodPessoaVendedor write FCodPessoaVendedor;
    property NomVendedor: String read FNomVendedor write FNomVendedor;
    property NumCNPJCPFVendedor: String read FNumCNPJCPFVendedor write FNumCNPJCPFVendedor;
    property QtdAnimais: Integer read FQtdAnimais write FQtdAnimais;
    property NumSolicitacaoSISBOV: Integer read FNumSolicitacaoSISBOV write FNumSolicitacaoSISBOV;
    property CodPaisSISBOVInicial: Integer read FCodPaisSISBOVInicial write FCodPaisSISBOVInicial;
    property CodEstadoSISBOVInicial: Integer read FCodEstadoSISBOVInicial write FCodEstadoSISBOVInicial;
    property CodMicroRegiaoSISBOVInicial: Integer read FCodMicroRegiaoSISBOVInicial write FCodMicroRegiaoSISBOVInicial;
    property CodAnimalSISBOVInicial: Integer read FCodAnimalSISBOVInicial write FCodAnimalSISBOVInicial;
    property NumDVSISBOVInicial: Integer read FNumDVSISBOVInicial write FNumDVSISBOVInicial;
    property CodFormaPagamentoOS: Integer read FCodFormaPagamentoOS write FCodFormaPagamentoOS;
    property DesFormaPagamentoOS: String read FFDesFormaPagamentoOS write FFDesFormaPagamentoOS;
    property EnderecoEntregaCert: TIntEndereco read FEnderecoEntregaCert write FEnderecoEntregaCert;
    property CodIdentificacaoDupla: Integer read FCodIdentificacaoDupla write FCodIdentificacaoDupla;
    property SglIdentificacaoDupla: String read FSglIdentificacaoDupla write FSglIdentificacaoDupla;
    property DesIdentificacaoDupla: String read FDesIdentificacaoDupla write FDesIdentificacaoDupla;
    property CodFabricanteIdentificador: Integer read FCodFabricanteIdentificador write FCodFabricanteIdentificador;
    property NomReduzidoFabricante: String read FNomReduzidoFabricante write FNomReduzidoFabricante;
    property CodformaPagamentoIdent: Integer read FCodformaPagamentoIdent write FCodformaPagamentoIdent;
    property DesFormaPagamentoIdent: String read FDesFormaPagamentoIdent write FDesFormaPagamentoIdent;
    property EnderecoEntregaIdent: TIntEndereco read FEnderecoEntregaIdent write FEnderecoEntregaIdent;
    property EnderecoCobrancaIdent: TIntEndereco read FEnderecoCobrancaIdent write FEnderecoCobrancaIdent;
    property CodModeloIdentificador1: Integer read FCodModeloIdentificador1 write FCodModeloIdentificador1;
    property SglModeloIdentificador1: String read FSglModeloIdentificador1 write FSglModeloIdentificador1;
    property DesModeloIdentificador1: String read FDesModeloIdentificador1 write FDesModeloIdentificador1;
    property CodModeloIdentificador2: Integer read FCodModeloIdentificador2 write FCodModeloIdentificador2;
    property SglModeloIdentificador2: String read FSglModeloIdentificador2 write FSglModeloIdentificador2;
    property DesModeloIdentificador2: String read FDesModeloIdentificador2 write FDesModeloIdentificador2;
    property CodProdutoAcessorio1: Integer read FCodProdutoAcessorio1 write FCodProdutoAcessorio1;
    property SglProdutoAcessorio1: String read FSglProdutoAcessorio1 write FSglProdutoAcessorio1;
    property DesProdutoAcessorio1: String read FDesProdutoAcessorio1 write FDesProdutoAcessorio1;
    property QtdProdutoAcessorio1: Integer read FQtdProdutoAcessorio1 write FQtdProdutoAcessorio1;
    property CodProdutoAcessorio2: Integer read FCodProdutoAcessorio2 write FCodProdutoAcessorio2;
    property SglProdutoAcessorio2: String read FSglProdutoAcessorio2 write FSglProdutoAcessorio2;
    property DesProdutoAcessorio2: String read FDesProdutoAcessorio2 write FDesProdutoAcessorio2;
    property QtdProdutoAcessorio2: Integer read FQtdProdutoAcessorio2 write FQtdProdutoAcessorio2;
    property CodProdutoAcessorio3: Integer read FCodProdutoAcessorio3 write FCodProdutoAcessorio3;
    property SglProdutoAcessorio3: String read FSglProdutoAcessorio3 write FSglProdutoAcessorio3;
    property DesProdutoAcessorio3: String read FDesProdutoAcessorio3 write FDesProdutoAcessorio3;
    property QtdProdutoAcessorio3: Integer read FQtdProdutoAcessorio3 write FQtdProdutoAcessorio3;
    property NumPedidoFabricante: Integer read FNumPedidoFabricante write FNumPedidoFabricante;
    property CodArquivoRemessaPedido: Integer read FCodArquivoRemessaPedido write FCodArquivoRemessaPedido;
    property NumRemessa: Integer read FNumRemessa write FNumRemessa;
    property DtaCadastramento: TDateTime read FDtaCadastramento write FDtaCadastramento;
    property CodUsuarioCadastramento: Integer read FCodUsuarioCadastramento write FCodUsuarioCadastramento;
    property NomUsuariocadastramento: String read FNomUsuariocadastramento write FNomUsuariocadastramento;
    property DtaUltimaAlteracao: TDateTime read FDtaUltimaAlteracao write FDtaUltimaAlteracao;
    property CodUsuarioUltimaAlteracao: Integer read FCodUsuarioUltimaAlteracao write FCodUsuarioUltimaAlteracao;
    property NomUsuarioUltimaAlteracao: String read FNomUsuarioUltimaAlteracao write FNomUsuarioUltimaAlteracao;
    property CodSituacaoOS: Integer read FCodSituacaoOS write FCodSituacaoOS;
    property SglSituacaoOS: String read FSglSituacaoOS write FSglSituacaoOS;
    property DesSituacaoOS: String read FDesSituacaoOS write FDesSituacaoOS;
    property TxtObservacao: String read FTxtObservacao write FTxtObservacao;
    property NumCNPJCPFProdutorFormatado: String read FNumCNPJCPFProdutorFormatado write FNumCNPJCPFProdutorFormatado;
    property NumCNPJCPFTecnicoFormatado: String read FNumCNPJCPFTecnicoFormatado write FNumCNPJCPFTecnicoFormatado;
    property NumCNPJCPFVendedorFormatado: String read FNumCNPJCPFVendedorFormatado write FNumCNPJCPFVendedorFormatado;
    property IndEnviaPedidoIdentificador: String read FIndEnviaPedidoIdentificador write FIndEnviaPedidoIdentificador;
    property NomUsuarioPedido: String read FNomUsuarioPedido write FNomUsuarioPedido;
    property CodUsuarioPedido: Integer read FCodUsuarioPedido write FCodUsuarioPedido;
    property DtaPedido: TDateTime read FDtaPedido write FDtaPedido;
    property TxtObservacaoPedido: String read FTxtObservacaoPedido write FTxtObservacaoPedido;
    property IndAnimaisRegistrados: String read FIndAnimaisRegistrados write FIndAnimaisRegistrados;
    property DtaEnvio: TDateTime read FDtaEnvio write FDtaEnvio;
    property NomServicoEnvio: String read FNomServicoEnvio write FNomServicoEnvio;
    property NumConhecimento: String read FNumConhecimento write FNumConhecimento;
    property CodLocalizacaoSisbov: Integer read FCodLocalizacaoSisbov write FCodLocalizacaoSisbov;
    property CodBoleto: Integer read FCodBoleto write FCodBoleto;
    property IndTransmissaoSisbov: String read FIndTransmissaoSisbov write FIndTransmissaoSisbov;
  end;

implementation

end.
