unit uIntEvento;

interface

type
  TIntEvento = class
  private
    FCodArquivoSisbov: Integer;
    FCodEvento: Integer;
    FCodGrupoEvento: Integer;
    FCodPessoaProdutor: Integer;
    FCodTipoEvento: Integer;
    FDesGrupoEvento: String;
    FDesTipoEvento: String;
    FDtaCadastramento: TDateTime;
    FDtaEfetivacaoCadastro: TDateTime;
    FDtaFim: TDateTime;
    FDtaGravacaoSisbov: TDateTime;
    FDtaInicio: TDateTime;
    FNomArquivoSisbov: String;
    FQtdAnimais: Integer;
    FSglGrupoEvento: String;
    FSglTipoEvento: String;
    FTxtDados: String;
    FTxtObservacao: String;
    FCodSituacaoSisbov: String;
    FCodAptidao: Integer;
    FCodCategoria: Integer;
    FCodFazenda: Integer;
    FNIRF: String;
    FCodLocalizacaoSISBOV: Integer;
    FCNPJAglomeracao: String;
    FNomArquivoCertificado: String;
    FCodPropriedadeRural: Integer;
    FNomPropriedadeRural: String;
    FNumCNPJCPFPessoa: String;
    FCodPessoa: Integer;
    FNomPessoa: String;
    FNumCNPJCPFPessoaSecundaria: String;
    FCodPessoaSecundaria: Integer;
    FNomPessoaSecundaria: String;
    FNumGTA: String;
    FCodSerieGta: String;
    FCodEstadoGta: Integer;
    FDtaEmissaoGTA: TDateTime;
    FDtaValidadeGTA: TDateTime;
    FCodAnimalRMManejo: String;
    FCodFazendaManejo: Integer;
    FCodPessoaSecAvaliador: Integer;
    FCodTipoAvaliacao: Integer;
    FCodGrauDificuldade: Integer;
    FCodEventoCobertura: Integer;
    FDesSituacaoCria: String;
    FDtaEventoCobertura: TDateTime;
    FQtdDiasGestacao: Integer;
    FNumOrdemParto: Integer;
    FCodAnimalManejoCria: String;
    FCodAnimalManejoGemeo: String;
    FCodAnimalManejoTouro: String;
    FCodAnimalManejoFemea: String;
    FCodEstacaoMonta: Integer;
    FCodAnimalTouro: Integer;
    FCodAnimalFemea: Integer;
    FCodPessoaOrigem: Integer;
    FCodPessoaDestino: Integer;
    FCodEventoAssociado: Integer;
    FIndVendaCertifTerceira: String;
    FCodExportacaoPropriedade: String;
    FIndMovNErasEras: String;
    FIndMigrarAnimal: String;
  public
    property CodArquivoSisbov: Integer read FCodArquivoSisbov write FCodArquivoSisbov;
    property CodEvento: Integer read FCodEvento write FCodEvento;
    property CodGrupoEvento: Integer read FCodGrupoEvento write FCodGrupoEvento;
    property CodPessoaProdutor: Integer read FCodPessoaProdutor write FCodPessoaProdutor;
    property CodTipoEvento: Integer read FCodTipoEvento write FCodTipoEvento;
    property DesGrupoEvento: String read FDesGrupoEvento write FDesGrupoEvento;
    property DesTipoEvento: String read FDesTipoEvento write FDesTipoEvento;
    property DtaCadastramento: TDateTime read FDtaCadastramento write FDtaCadastramento;
    property DtaEfetivacaoCadastro: TDateTime read FDtaEfetivacaoCadastro write FDtaEfetivacaoCadastro;
    property DtaFim: TDateTime read FDtaFim write FDtaFim;
    property DtaGravacaoSisbov: TDateTime read FDtaGravacaoSisbov write FDtaGravacaoSisbov;
    property DtaInicio: TDateTime read FDtaInicio write FDtaInicio;
    property NomArquivoSisbov: String read FNomArquivoSisbov write FNomArquivoSisbov;
    property QtdAnimais: Integer read FQtdAnimais write FQtdAnimais;
    property SglGrupoEvento: String read FSglGrupoEvento write FSglGrupoEvento;
    property SglTipoEvento: String read FSglTipoEvento write FSglTipoEvento;
    property TxtDados: String read FTxtDados write FTxtDados;
    property TxtObservacao: String read FTxtObservacao write FTxtObservacao;
    property CodSituacaoSisbov: String read FCodSituacaoSisbov write FCodSituacaoSisbov;
    property CodAptidao: Integer read FCodAptidao write FCodAptidao;
    property CodCategoria: Integer read FCodCategoria write FCodCategoria;
    property CodFazenda: Integer read FCodFazenda write FCodFazenda;
    property NIRF: String read FNIRF write FNIRF;
    property CodLocalizacaoSISBOV: Integer read FCodLocalizacaoSISBOV write FCodLocalizacaoSISBOV;
    property CNPJAglomeracao: String read FCNPJAglomeracao write FCNPJAglomeracao;
    property NomArquivoCertificado: String read FNomArquivoCertificado write FNomArquivoCertificado;
    property CodPropriedadeRural: Integer read FCodPropriedadeRural write FCodPropriedadeRural;
    property NomPropriedadeRural: String read FNomPropriedadeRural write FNomPropriedadeRural;
    property NumCNPJCPFPessoa: String read FNumCNPJCPFPessoa write FNumCNPJCPFPessoa;
    property CodPessoa: Integer read FCodPessoa write FCodPessoa;
    property NomPessoa: String read FNomPessoa write FNomPessoa;
    property NumCNPJCPFPessoaSecundaria: String read FNumCNPJCPFPessoaSecundaria write FNumCNPJCPFPessoaSecundaria;
    property CodPessoaSecundaria: Integer read FCodPessoaSecundaria write FCodPessoaSecundaria;
    property NomPessoaSecundaria: String read FNomPessoaSecundaria write FNomPessoaSecundaria;
    property NumGTA: String read FNumGTA write FNumGTA;
    property CodSerieGTA: String read FCodSerieGTA write FCodSerieGTA;
    property CodEstadoGTA: Integer read FCodEstadoGTA write FCodEstadoGTA;
    property DtaEmissaoGTA: TDateTime read FDtaEmissaoGTA write FDtaEmissaoGTA;
    property DtaValidadeGTA: TDateTime read FDtaValidadeGTA write FDtaValidadeGTA;
    property CodAnimalRMManejo: String read FCodAnimalRMManejo write FCodAnimalRMManejo;
    property CodFazendaManejo: Integer read FCodFazendaManejo write FCodFazendaManejo;
    property CodPessoaSecAvaliador: Integer read FCodPessoaSecAvaliador write FCodPessoaSecAvaliador;
    property CodTipoAvaliacao: Integer read FCodTipoAvaliacao write FCodTipoAvaliacao;
    property CodGrauDificuldade: Integer read FCodGrauDificuldade write FCodGrauDificuldade;
    property CodEventoCobertura: Integer read FCodEventoCobertura write FCodEventoCobertura;
    property DesSituacaoCria: String read FDesSituacaoCria write FDesSituacaoCria;
    property DtaEventoCobertura: TDateTime read FDtaEventoCobertura write FDtaEventoCobertura;
    property QtdDiasGestacao: Integer read FQtdDiasGestacao write FQtdDiasGestacao;
    property NumOrdemParto: Integer read FNumOrdemParto write FNumOrdemParto;
    property CodAnimalManejoCria: String read FCodAnimalManejoCria write FCodAnimalManejoCria;
    property CodAnimalManejoGemeo: String read FCodAnimalManejoGemeo write FCodAnimalManejoGemeo;
    property CodAnimalManejoTouro: String read FCodAnimalManejoTouro write FCodAnimalManejoTouro;
    property CodAnimalManejoFemea: String read FCodAnimalManejoFemea write FCodAnimalManejoFemea;
    property CodEstacaoMonta: Integer read FCodEstacaoMonta write FCodEstacaoMonta;
    property CodAnimalTouro: Integer read FCodAnimalTouro write FCodAnimalTouro;
    property CodAnimalFemea: Integer read FCodAnimalFemea write FCodAnimalFemea;
    property CodPessoaOrigem: Integer read FCodPessoaOrigem write FCodPessoaOrigem;
    property CodPessoaDestino: Integer read FCodPessoaDestino write FCodPessoaDestino;
    property CodEventoAssociado: Integer read FCodEventoAssociado write FCodEventoAssociado;
    property IndVendaCertifTerceira: String read FIndVendaCertifTerceira write FIndVendaCertifTerceira;
    property CodExportacaoPropriedade: String read FCodExportacaoPropriedade write FCodExportacaoPropriedade;
    property IndMovNErasEras: String read FIndMovNErasEras write FIndMovNErasEras;
    property IndMigrarAnimal: String read FIndMigrarAnimal write FIndMigrarAnimal;
  end;

implementation

end.
